[build]
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/gemini-chat"
  to = "/.netlify/functions/gemini-chat"
  status = 200
